name: checkpay
description: Simple School Fee Tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  local_auth: ^2.3.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  crypto: ^3.0.3
  share_plus: ^10.1.4
  file_selector: ^1.0.3
  path: ^1.9.0
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'lib/public/android-chrome-512x512.png'
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - lib/public/android-chrome-192x192.png
    - lib/public/android-chrome-512x512.png
    - lib/public/apple-touch-icon.png
    - lib/public/favicon-32x32.png
    - lib/public/favicon-16x16.png
